---
version: "2.0"

services:
  frontend:
    image: ghcr.io/emmadorably/rose-token-v3/rose-frontend:latest
    expose:
      - port: 80
        as: 80
        accept:
          - dev.rose-token.com
        to:
          - global: true
    # Note: All VITE_* env vars are baked into the image at build time
    # No runtime env vars needed for the frontend

profiles:
  compute:
    frontend:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 256Mi
        storage:
          - size: 512Mi

  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        frontend:
          denom: uakt
          amount: 500

deployment:
  frontend:
    dcloud:
      profile: frontend
      count: 1
