import { ethers } from 'ethers';
import { config } from '../config';
import { getWsProvider } from './wsProvider';

// Import ABIs from JSON files (generated by npm run update-abi)
import RoseMarketplaceABI from '../abis/RoseMarketplaceABI.json';
import RoseTokenABI from '../abis/RoseTokenABI.json';
import RoseTreasuryABI from '../abis/RoseTreasuryABI.json';
import vROSEABI from '../abis/vROSEABI.json';
import RoseGovernanceABI from '../abis/RoseGovernanceABI.json';
import RoseReputationABI from '../abis/RoseReputationABI.json';

// Re-export ABIs for services that need direct access
export {
  RoseMarketplaceABI,
  RoseTokenABI,
  RoseTreasuryABI,
  vROSEABI,
  RoseGovernanceABI,
  RoseReputationABI,
};

// HTTP provider for queryFilter operations (startup catch-up)
let httpProvider: ethers.JsonRpcProvider | null = null;

/**
 * Get HTTP provider for non-subscription operations (queryFilter, etc.)
 */
export function getHttpProvider(): ethers.JsonRpcProvider {
  if (!httpProvider) {
    httpProvider = new ethers.JsonRpcProvider(config.rpc.url);
  }
  return httpProvider;
}

/**
 * Get Marketplace contract instance
 */
export function getMarketplaceContract(
  signerOrProvider?: ethers.Signer | ethers.Provider
): ethers.Contract {
  if (!config.contracts.marketplace) {
    throw new Error('MARKETPLACE_ADDRESS not configured');
  }
  return new ethers.Contract(
    config.contracts.marketplace,
    RoseMarketplaceABI,
    signerOrProvider || getWsProvider()
  );
}

/**
 * Get Governance contract instance
 */
export function getGovernanceContract(
  signerOrProvider?: ethers.Signer | ethers.Provider
): ethers.Contract {
  if (!config.contracts.governance) {
    throw new Error('GOVERNANCE_ADDRESS not configured');
  }
  return new ethers.Contract(
    config.contracts.governance,
    RoseGovernanceABI,
    signerOrProvider || getWsProvider()
  );
}

/**
 * Get Treasury contract instance
 */
export function getTreasuryContract(
  signerOrProvider?: ethers.Signer | ethers.Provider
): ethers.Contract {
  if (!config.contracts.treasury) {
    throw new Error('TREASURY_ADDRESS not configured');
  }
  return new ethers.Contract(
    config.contracts.treasury,
    RoseTreasuryABI,
    signerOrProvider || getWsProvider()
  );
}

/**
 * Get Reputation contract instance
 */
export function getReputationContract(
  signerOrProvider?: ethers.Signer | ethers.Provider
): ethers.Contract {
  if (!config.contracts.reputation) {
    throw new Error('REPUTATION_ADDRESS not configured');
  }
  return new ethers.Contract(
    config.contracts.reputation,
    RoseReputationABI,
    signerOrProvider || getWsProvider()
  );
}

/**
 * Get Token contract instance
 */
export function getTokenContract(
  signerOrProvider?: ethers.Signer | ethers.Provider
): ethers.Contract {
  // Token address not in config, but we export the ABI for completeness
  throw new Error('TOKEN_ADDRESS not configured in backend config');
}

/**
 * Get vROSE contract instance
 */
export function getVRoseContract(
  signerOrProvider?: ethers.Signer | ethers.Provider
): ethers.Contract {
  // vROSE address not in config, but we export the ABI for completeness
  throw new Error('VROSE_ADDRESS not configured in backend config');
}
