export const NETWORK_IDS = {
  MAINNET: 1,
  OP_SEPOLIA: 11155420
};

export const NETWORK_NAMES = {
  [NETWORK_IDS.MAINNET]: 'Ethereum Mainnet',
  [NETWORK_IDS.OP_SEPOLIA]: 'Optimism Sepolia'
};

export const SUPPORTED_NETWORKS = [
  { id: NETWORK_IDS.OP_SEPOLIA, name: NETWORK_NAMES[NETWORK_IDS.OP_SEPOLIA] },
  { id: NETWORK_IDS.MAINNET, name: NETWORK_NAMES[NETWORK_IDS.MAINNET] }
];

export const DEFAULT_NETWORK = NETWORK_IDS.OP_SEPOLIA;
