export const NETWORK_IDS = {
  MAINNET: 1,
  SEPOLIA: 11155111,
  HOODI: 560048
};

export const NETWORK_NAMES = {
  [NETWORK_IDS.MAINNET]: 'Ethereum Mainnet',
  [NETWORK_IDS.SEPOLIA]: 'Sepolia Testnet',
  [NETWORK_IDS.HOODI]: 'Hoodi Testnet'
};

export const SUPPORTED_NETWORKS = [
  { id: NETWORK_IDS.HOODI, name: NETWORK_NAMES[NETWORK_IDS.HOODI] },
  { id: NETWORK_IDS.SEPOLIA, name: NETWORK_NAMES[NETWORK_IDS.SEPOLIA] },
  { id: NETWORK_IDS.MAINNET, name: NETWORK_NAMES[NETWORK_IDS.MAINNET] }
];

export const DEFAULT_NETWORK = NETWORK_IDS.HOODI;
